/* automatically generated by rust-bindgen 0.71.1 */

pub const __USING_MINT8: u32 = 0;
#[doc = " \\ingroup avr_stdint\nsigned int with at least 8 bits."]
pub type int_least8_t = i8;
#[doc = " \\ingroup avr_stdint\nunsigned int with at least 8 bits."]
pub type uint_least8_t = u8;
#[doc = " \\ingroup avr_stdint\nsigned int with at least 16 bits."]
pub type int_least16_t = i16;
#[doc = " \\ingroup avr_stdint\nunsigned int with at least 16 bits."]
pub type uint_least16_t = u16;
#[doc = " \\ingroup avr_stdint\nsigned int with at least 32 bits."]
pub type int_least32_t = i32;
#[doc = " \\ingroup avr_stdint\nunsigned int with at least 32 bits."]
pub type uint_least32_t = u32;
#[doc = " \\ingroup avr_stdint\nsigned int with at least 64 bits.\n\\note This type is not available when the compiler\noption -mint8 is in effect."]
pub type int_least64_t = i64;
#[doc = " \\ingroup avr_stdint\nunsigned int with at least 64 bits.\n\\note This type is not available when the compiler\noption -mint8 is in effect."]
pub type uint_least64_t = u64;
#[doc = " \\ingroup avr_stdint\nfastest signed int with at least 8 bits."]
pub type int_fast8_t = i8;
#[doc = " \\ingroup avr_stdint\nfastest unsigned int with at least 8 bits."]
pub type uint_fast8_t = u8;
#[doc = " \\ingroup avr_stdint\nfastest signed int with at least 16 bits."]
pub type int_fast16_t = i16;
#[doc = " \\ingroup avr_stdint\nfastest unsigned int with at least 16 bits."]
pub type uint_fast16_t = u16;
#[doc = " \\ingroup avr_stdint\nfastest signed int with at least 32 bits."]
pub type int_fast32_t = i32;
#[doc = " \\ingroup avr_stdint\nfastest unsigned int with at least 32 bits."]
pub type uint_fast32_t = u32;
#[doc = " \\ingroup avr_stdint\nfastest signed int with at least 64 bits.\n\\note This type is not available when the compiler\noption -mint8 is in effect."]
pub type int_fast64_t = i64;
#[doc = " \\ingroup avr_stdint\nfastest unsigned int with at least 64 bits.\n\\note This type is not available when the compiler\noption -mint8 is in effect."]
pub type uint_fast64_t = u64;
#[doc = " \\ingroup avr_stdint\nlargest signed int available."]
pub type intmax_t = i64;
#[doc = " \\ingroup avr_stdint\nlargest unsigned int available."]
pub type uintmax_t = u64;
#[repr(u8)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum Button {
    Up = 0,
    Down = 1,
    TempHeat = 2,
    TempCold = 3,
    TempNone = 4,
    FanAuto = 5,
    FanOn = 6,
}
#[repr(u8)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum Relay {
    Fan = 0,
    Compressor = 1,
    Heat = 2,
    ReversingValve = 3,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct AvrDriverCallbacks {
    pub OnButtonPressed:
        ::core::option::Option<unsafe extern "C" fn(b: Button, userData: *mut ::core::ffi::c_void)>,
    pub OnSerialMessage: ::core::option::Option<
        unsafe extern "C" fn(
            message: *const ::core::ffi::c_char,
            messageLen: u16,
            userData: *mut ::core::ffi::c_void,
        ),
    >,
    pub OnSecondPassed:
        ::core::option::Option<unsafe extern "C" fn(userData: *mut ::core::ffi::c_void)>,
}
extern "C" {
    pub fn DriverInit(callbacks: *const AvrDriverCallbacks, userData: *mut ::core::ffi::c_void);
    pub fn DriverDisplayTemp(temp: u8);
    pub fn DriverDisplaySetPoint(temp: u8);
    pub fn DriverDisplayIsHeating();
    pub fn DriverDisplayIsCooling();
    pub fn DriverReadTemp() -> u8;
    pub fn DriverDisplayIsIdle();
    pub fn DriverRelayOn(r: Relay);
    pub fn DriverRelayOff(r: Relay);
    pub fn DriverWriteSerialPort(bytes: *const u8, numBytes: u8);
}
