/* automatically generated by rust-bindgen 0.71.1 */

pub const __USING_MINT8: u32 = 0;
#[doc = " \\ingroup avr_stdint\nsigned int with at least 8 bits."]
pub type int_least8_t = i8;
#[doc = " \\ingroup avr_stdint\nunsigned int with at least 8 bits."]
pub type uint_least8_t = u8;
#[doc = " \\ingroup avr_stdint\nsigned int with at least 16 bits."]
pub type int_least16_t = i16;
#[doc = " \\ingroup avr_stdint\nunsigned int with at least 16 bits."]
pub type uint_least16_t = u16;
#[doc = " \\ingroup avr_stdint\nsigned int with at least 32 bits."]
pub type int_least32_t = i32;
#[doc = " \\ingroup avr_stdint\nunsigned int with at least 32 bits."]
pub type uint_least32_t = u32;
#[doc = " \\ingroup avr_stdint\nsigned int with at least 64 bits.\n\\note This type is not available when the compiler\noption -mint8 is in effect."]
pub type int_least64_t = i64;
#[doc = " \\ingroup avr_stdint\nunsigned int with at least 64 bits.\n\\note This type is not available when the compiler\noption -mint8 is in effect."]
pub type uint_least64_t = u64;
#[doc = " \\ingroup avr_stdint\nfastest signed int with at least 8 bits."]
pub type int_fast8_t = i8;
#[doc = " \\ingroup avr_stdint\nfastest unsigned int with at least 8 bits."]
pub type uint_fast8_t = u8;
#[doc = " \\ingroup avr_stdint\nfastest signed int with at least 16 bits."]
pub type int_fast16_t = i16;
#[doc = " \\ingroup avr_stdint\nfastest unsigned int with at least 16 bits."]
pub type uint_fast16_t = u16;
#[doc = " \\ingroup avr_stdint\nfastest signed int with at least 32 bits."]
pub type int_fast32_t = i32;
#[doc = " \\ingroup avr_stdint\nfastest unsigned int with at least 32 bits."]
pub type uint_fast32_t = u32;
#[doc = " \\ingroup avr_stdint\nfastest signed int with at least 64 bits.\n\\note This type is not available when the compiler\noption -mint8 is in effect."]
pub type int_fast64_t = i64;
#[doc = " \\ingroup avr_stdint\nfastest unsigned int with at least 64 bits.\n\\note This type is not available when the compiler\noption -mint8 is in effect."]
pub type uint_fast64_t = u64;
#[doc = " \\ingroup avr_stdint\nlargest signed int available."]
pub type intmax_t = i64;
#[doc = " \\ingroup avr_stdint\nlargest unsigned int available."]
pub type uintmax_t = u64;
pub const Button_Up: Button = 0;
pub const Button_Down: Button = 1;
pub const Button_TempHeat: Button = 2;
pub const Button_TempCold: Button = 3;
pub const Button_FanAuto: Button = 4;
pub const Button_FanOn: Button = 5;
pub type Button = u8;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct AvrDriverCallbacks {
    pub OnButtonPressed: ::std::option::Option<unsafe extern "C" fn(b: Button)>,
    pub OnTemperatureRead: ::std::option::Option<unsafe extern "C" fn(degreesC: u8)>,
    pub OnSerialMessage: ::std::option::Option<
        unsafe extern "C" fn(message: *const ::std::os::raw::c_char, messageLen: u16),
    >,
    pub OnSecondPassed: ::std::option::Option<unsafe extern "C" fn()>,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of AvrDriverCallbacks"][::std::mem::size_of::<AvrDriverCallbacks>() - 32usize];
    ["Alignment of AvrDriverCallbacks"][::std::mem::align_of::<AvrDriverCallbacks>() - 8usize];
    ["Offset of field: AvrDriverCallbacks::OnButtonPressed"]
        [::std::mem::offset_of!(AvrDriverCallbacks, OnButtonPressed) - 0usize];
    ["Offset of field: AvrDriverCallbacks::OnTemperatureRead"]
        [::std::mem::offset_of!(AvrDriverCallbacks, OnTemperatureRead) - 8usize];
    ["Offset of field: AvrDriverCallbacks::OnSerialMessage"]
        [::std::mem::offset_of!(AvrDriverCallbacks, OnSerialMessage) - 16usize];
    ["Offset of field: AvrDriverCallbacks::OnSecondPassed"]
        [::std::mem::offset_of!(AvrDriverCallbacks, OnSecondPassed) - 24usize];
};
unsafe extern "C" {
    pub fn DriverInit(callbacks: *const AvrDriverCallbacks);
}
unsafe extern "C" {
    pub fn DriverWriteScreen(message: *const ::std::os::raw::c_char, messageLen: u8);
}
unsafe extern "C" {
    pub fn DriverWriteSerialPort(bytes: *const u8, numBytes: u8);
}
