// Code generated by bitproto. DO NOT EDIT.

#ifndef __BITPROTO__HOME_ASSISTANT_SERIAL_H__
#define __BITPROTO__HOME_ASSISTANT_SERIAL_H__ 1

#include <inttypes.h>
#include <stddef.h>
#include <stdint.h>
#ifndef __cplusplus
#include <stdbool.h>
#endif

#if defined(__cplusplus)
extern "C" {
#endif

#define BITPROTO_OPTIMIZATION_MODE 1

typedef uint8_t HaTopicKey; // 8bit

#define ACTION_TOPIC 0
#define CURRENT_HUMIDITY_TOPIC 1
#define CURRENT_TEMP_TOPIC 2
#define FAN_MODE_COMMAND_TOPIC 3
#define FAN_MODE_STATE_TOPIC 4
#define MODE_COMMAND_TOPIC 5
#define MODE_STATE_TOPIC 6
#define POWER_COMMAND_TOPIC 7
#define TEMP_COMMAND_TOPIC 10
#define TEMP_STATE_TOPIC 11
#define MQTT_PING_TOPIC 12

typedef uint8_t HaActionTopicKey; // 3bit

#define HA_ACTION_OFF 0
#define HA_ACTION_HEATING 1
#define HA_ACTION_COOLING 2
#define HA_ACTION_IDLE 3
#define HA_ACTION_FAN 4

// Number of bytes to encode struct HaCommand
#define BYTES_LENGTH_HA_COMMAND 4

struct HaCommand {
    uint8_t checksum; // 8bit
    HaTopicKey topic_key; // 8bit
    uint8_t payload_byte_one; // 8bit
    uint8_t payload_byte_two; // 8bit
};

// Encode struct HaCommand to given buffer s.
int EncodeHaCommand(struct HaCommand *m, unsigned char *s);
// Decode struct HaCommand from given buffer s.
int DecodeHaCommand(struct HaCommand *m, unsigned char *s);

#if defined(__cplusplus)
}
#endif

#endif