// Code generated by bitproto. DO NOT EDIT.

#ifndef __BITPROTO__THERMO_SAVE_DATA_H__
#define __BITPROTO__THERMO_SAVE_DATA_H__ 1

#include <inttypes.h>
#include <stddef.h>
#include <stdint.h>
#ifndef __cplusplus
#include <stdbool.h>
#endif

#if defined(__cplusplus)
extern "C" {
#endif

#define BITPROTO_OPTIMIZATION_MODE 1

#define SAVEDATA_MAGIC 43996

#define WIFI_NAME_MAX_LEN 32

#define WIFI_NAME_MAX_LEN_W_NULL 33

#define WIFI_PASSWORD_MAX_LEN 64

#define WIFI_PASSWORD_MAX_LEN_W_NULL 65

typedef uint8_t TempDisplayUnit; // 1bit

#define TEMP_UNIT_FREEDOM 0
#define TEMP_UNIT_CELSIUS 1

typedef uint8_t FanMode; // 1bit

#define FANMODE_AUTO 0
#define FANMODE_ON 1

typedef uint8_t HeatMode; // 2bit

#define HEATMODE_HEAT 0
#define HEATMODE_COOL 1
#define HEATMODE_NONE 2

// Number of bytes to encode struct MqttConfig
#define BYTES_LENGTH_MQTT_CONFIG 98

struct MqttConfig {
    unsigned char wifi_name[33]; // 264bit
    unsigned char wifi_password[65]; // 520bit
};

// Number of bytes to encode struct ThermoSaveData
#define BYTES_LENGTH_THERMO_SAVE_DATA 105

struct ThermoSaveData {
    uint8_t checksum; // 8bit
    uint16_t magic; // 16bit
    uint16_t set_point_mibicelcius; // 16bit
    TempDisplayUnit temp_display_unit; // 1bit
    FanMode fan_mode; // 1bit
    HeatMode heat_mode; // 2bit
    uint8_t have_mqtt; // 8bit
    uint8_t pad; // 4bit
    struct MqttConfig mqtt; // 784bit
};

// Encode struct MqttConfig to given buffer s.
int EncodeMqttConfig(struct MqttConfig *m, unsigned char *s);
// Decode struct MqttConfig from given buffer s.
int DecodeMqttConfig(struct MqttConfig *m, unsigned char *s);

// Encode struct ThermoSaveData to given buffer s.
int EncodeThermoSaveData(struct ThermoSaveData *m, unsigned char *s);
// Decode struct ThermoSaveData from given buffer s.
int DecodeThermoSaveData(struct ThermoSaveData *m, unsigned char *s);

#if defined(__cplusplus)
}
#endif

#endif