// Code generated by bitproto. DO NOT EDIT.

#include "ThermoSaveData_bp.h"
#include <string.h>

int EncodeMqttConfig(struct MqttConfig *m, unsigned char *s) {
    memcpy(&s[0], (*m).wifi_name, 33);
    memcpy(&s[33], (*m).wifi_password, 65);
    return 0;
}

int DecodeMqttConfig(struct MqttConfig *m, unsigned char *s) {
    memcpy((*m).wifi_name, &s[0], 33);
    memcpy((*m).wifi_password, &s[33], 65);
    return 0;
}

int EncodeThermoSaveData(struct ThermoSaveData *m, unsigned char *s) {
    s[0] = (((unsigned char *)&((*m).checksum))[0] ) & 255;
    s[1] = (((unsigned char *)&((*m).magic))[0] ) & 255;
    s[2] = (((unsigned char *)&((*m).magic))[1] ) & 255;
    s[3] = (((unsigned char *)&((*m).set_point_mibicelcius))[0] ) & 255;
    s[4] = (((unsigned char *)&((*m).set_point_mibicelcius))[1] ) & 255;
    s[5] = (((unsigned char *)&((*m).temp_display_unit))[0] ) & 1;
    s[5] |= (((unsigned char *)&((*m).fan_mode))[0] << 1) & 2;
    s[5] |= (((unsigned char *)&((*m).heat_mode))[0] << 2) & 12;
    s[5] |= (((unsigned char *)&((*m).have_mqtt))[0] << 4) & 240;
    s[6] = (((unsigned char *)&((*m).have_mqtt))[0] >> 4) & 15;
    s[6] |= (((unsigned char *)&((*m).pad))[0] << 4) & 240;
    memcpy(&s[7], (*m).mqtt.wifi_name, 33);
    memcpy(&s[40], (*m).mqtt.wifi_password, 65);
    return 0;
}

int DecodeThermoSaveData(struct ThermoSaveData *m, unsigned char *s) {
    ((unsigned char *)&((*m).checksum))[0] = (s[0] ) & 255;
    ((unsigned char *)&((*m).magic))[0] = (s[1] ) & 255;
    ((unsigned char *)&((*m).magic))[1] = (s[2] ) & 255;
    ((unsigned char *)&((*m).set_point_mibicelcius))[0] = (s[3] ) & 255;
    ((unsigned char *)&((*m).set_point_mibicelcius))[1] = (s[4] ) & 255;
    ((unsigned char *)&((*m).temp_display_unit))[0] = (s[5] ) & 1;
    ((unsigned char *)&((*m).fan_mode))[0] = (s[5] >> 1) & 1;
    ((unsigned char *)&((*m).heat_mode))[0] = (s[5] >> 2) & 3;
    ((unsigned char *)&((*m).have_mqtt))[0] = (s[5] >> 4) & 15;
    ((unsigned char *)&((*m).have_mqtt))[0] |= (s[6] << 4) & 240;
    ((unsigned char *)&((*m).pad))[0] = (s[6] >> 4) & 15;
    memcpy((*m).mqtt.wifi_name, &s[7], 33);
    memcpy((*m).mqtt.wifi_password, &s[40], 65);
    return 0;
}