proto ThermoSaveData

const THERMO_STATE_DATA_MAGIC = 45
const WIFI_NAME_MAX_LEN = 32
const WIFI_NAME_MAX_LEN_W_NULL = 33
const WIFI_PASSWORD_MAX_LEN = 64
const WIFI_PASSWORD_MAX_LEN_W_NULL = 65

enum TempDisplayUnit : uint1 {
    TEMP_UNIT_FREEDOM = 0
    TEMP_UNIT_CELSIUS = 1
}

enum TimeAmPm : uint1 {
    TIME_AM = 0
    TIME_PM = 1
}

message Time {
    uint5 hour = 1
    uint8 minute = 2
    uint8 second = 3
    TimeAmPm am_pm = 4
}

enum FanMode : uint1 {
    FANMODE_AUTO = 0
    FANMODE_ON = 1
}

enum HeatMode : uint2 {
    HEATMODE_HEAT = 0
    HEATMODE_COOL = 1
    HEATMODE_NONE = 2
}

enum DateDayOfWeek : uint4 {
    DAYOFWEEK_SUNDAY = 0
    DAYOFWEEK_MONDAY = 1
    DAYOFWEEK_TUESDAY = 2
    DAYOFWEEK_WEDNESDAY = 3
    DAYOFWEEK_THURSDAY = 4
    DAYOFWEEK_FRIDAY = 5
    DAYOFWEEK_SATURDAY = 6
}

message Date {
    uint8 year = 1
    uint4 month = 2
    uint5 day = 3
    DateDayOfWeek day_of_week = 4
}

message MqttConfig {
    byte[WIFI_NAME_MAX_LEN_W_NULL] wifi_name = 1
    byte[WIFI_PASSWORD_MAX_LEN_W_NULL] wifi_password = 2
}

message ThermoSaveData {
    uint8 magic = 1
    uint8 set_point = 2
    TempDisplayUnit temp_display_unit = 3
    Date date = 4
    Time time = 5
    FanMode fan_mode = 6
    HeatMode heat_mode = 7
    uint1 pad = 8
    uint8 have_mqtt = 9
    MqttConfig mqtt = 10
}
