proto ThermoSaveData

const SAVEDATA_MAGIC = 0xABDC

const WIFI_NAME_MAX_LEN = 32
const WIFI_NAME_MAX_LEN_W_NULL = 33
const WIFI_PASSWORD_MAX_LEN = 64
const WIFI_PASSWORD_MAX_LEN_W_NULL = 65

enum TempDisplayUnit : uint1 {
    TEMP_UNIT_FREEDOM = 0
    TEMP_UNIT_CELSIUS = 1
}

enum FanMode : uint1 {
    FANMODE_AUTO = 0
    FANMODE_ON = 1
}

enum HeatMode : uint2 {
    HEATMODE_HEAT = 0
    HEATMODE_COOL = 1
    HEATMODE_NONE = 2
}

message MqttConfig {
    byte[WIFI_NAME_MAX_LEN_W_NULL] wifi_name = 1
    byte[WIFI_PASSWORD_MAX_LEN_W_NULL] wifi_password = 2
}

message ThermoSaveData {
    uint8 checksum = 1
    uint16 magic = 2
    uint16 set_point_mibicelcius = 3
    TempDisplayUnit temp_display_unit = 4
    FanMode fan_mode = 5
    HeatMode heat_mode = 6
    uint8 have_mqtt = 7
    uint4 pad = 8
    MqttConfig mqtt = 9
}
