[package]
name = "thermo-app-avr"
version = "0.1.0"
authors = ["Dylan McKay <me@dylanmckay.io>"]
edition = '2021'

[lib]
name = "thermoapp"
crate-type = ["staticlib"]

[dependencies]
thermo-app = { path = "../thermo-app" }

[profile.dev]
lto = true
panic = "abort"

[profile.release]
lto = true
panic = "abort"

[profile.test]
lto = true
panic = "abort"
