// Code generated by bitproto. DO NOT EDIT.

#ifndef __BITPROTO__THERMO_COMM_EVENT_H__
#define __BITPROTO__THERMO_COMM_EVENT_H__ 1

#include <inttypes.h>
#include <stddef.h>
#include <stdint.h>
#ifndef __cplusplus
#include <stdbool.h>
#endif

#if defined(__cplusplus)
extern "C" {
#endif

#include "ThermoSaveData_bp.h"

#define BITPROTO_OPTIMIZATION_MODE 1

// Number of bytes to encode struct TempChangedEvent
#define BYTES_LENGTH_TEMP_CHANGED_EVENT 1

struct TempChangedEvent {
    uint8_t new_temp_f; // 8bit
};

// Number of bytes to encode struct SetPointChangedEvent
#define BYTES_LENGTH_SET_POINT_CHANGED_EVENT 1

struct SetPointChangedEvent {
    uint8_t new_set_point_f; // 8bit
};

typedef uint8_t HeatingCommMode; // 2bit

#define HEATING_COMM_HEATING 0
#define HEATING_COMM_COOLING 1
#define HEATING_COMM_IDLE 2

// Number of bytes to encode struct HeatingModeChangedEvent
#define BYTES_LENGTH_HEATING_MODE_CHANGED_EVENT 1

struct HeatingModeChangedEvent {
    HeatingCommMode new_mode; // 2bit
};

// Number of bytes to encode struct SettingsChangedEvent
#define BYTES_LENGTH_SETTINGS_CHANGED_EVENT 4

struct SettingsChangedEvent {
    struct ThermoSaveData new_settings; // 25bit
};

// Encode struct TempChangedEvent to given buffer s.
int EncodeTempChangedEvent(struct TempChangedEvent *m, unsigned char *s);
// Decode struct TempChangedEvent from given buffer s.
int DecodeTempChangedEvent(struct TempChangedEvent *m, unsigned char *s);

// Encode struct SetPointChangedEvent to given buffer s.
int EncodeSetPointChangedEvent(struct SetPointChangedEvent *m, unsigned char *s);
// Decode struct SetPointChangedEvent from given buffer s.
int DecodeSetPointChangedEvent(struct SetPointChangedEvent *m, unsigned char *s);

// Encode struct HeatingModeChangedEvent to given buffer s.
int EncodeHeatingModeChangedEvent(struct HeatingModeChangedEvent *m, unsigned char *s);
// Decode struct HeatingModeChangedEvent from given buffer s.
int DecodeHeatingModeChangedEvent(struct HeatingModeChangedEvent *m, unsigned char *s);

// Encode struct SettingsChangedEvent to given buffer s.
int EncodeSettingsChangedEvent(struct SettingsChangedEvent *m, unsigned char *s);
// Decode struct SettingsChangedEvent from given buffer s.
int DecodeSettingsChangedEvent(struct SettingsChangedEvent *m, unsigned char *s);

#if defined(__cplusplus)
}
#endif

#endif