// Code generated by bitproto. DO NOT EDIT.

#ifndef __BITPROTO__THERMO_SAVE_DATA_H__
#define __BITPROTO__THERMO_SAVE_DATA_H__ 1

#include <inttypes.h>
#include <stddef.h>
#include <stdint.h>
#ifndef __cplusplus
#include <stdbool.h>
#endif

#if defined(__cplusplus)
extern "C" {
#endif

#define BITPROTO_OPTIMIZATION_MODE 1

#define THERMO_STATE_DATA_MAGIC 292

typedef uint8_t TempDisplayUnit; // 1bit

#define TEMP_UNIT_FREEDOM 0
#define TEMP_UNIT_CELSIUS 1

// Number of bytes to encode struct ThermoSaveData
#define BYTES_LENGTH_THERMO_SAVE_DATA 4

struct ThermoSaveData {
    uint16_t magic; // 16bit
    uint8_t set_point; // 8bit
    TempDisplayUnit temp_display_unit; // 1bit
};

// Encode struct ThermoSaveData to given buffer s.
int EncodeThermoSaveData(struct ThermoSaveData *m, unsigned char *s);
// Decode struct ThermoSaveData from given buffer s.
int DecodeThermoSaveData(struct ThermoSaveData *m, unsigned char *s);

#if defined(__cplusplus)
}
#endif

#endif