// Code generated by bitproto. DO NOT EDIT.

#include "ThermoSaveData_bp.h"

int EncodeThermoSaveData(struct ThermoSaveData *m, unsigned char *s) {
    s[0] = (((unsigned char *)&((*m).magic))[0] ) & 255;
    s[1] = (((unsigned char *)&((*m).magic))[1] ) & 255;
    s[2] = (((unsigned char *)&((*m).set_point))[0] ) & 255;
    s[3] = (((unsigned char *)&((*m).temp_display_unit))[0] ) & 1;
    return 0;
}

int DecodeThermoSaveData(struct ThermoSaveData *m, unsigned char *s) {
    ((unsigned char *)&((*m).magic))[0] = (s[0] ) & 255;
    ((unsigned char *)&((*m).magic))[1] = (s[1] ) & 255;
    ((unsigned char *)&((*m).set_point))[0] = (s[2] ) & 255;
    ((unsigned char *)&((*m).temp_display_unit))[0] = (s[3] ) & 1;
    return 0;
}