// Code generated by bitproto. DO NOT EDIT.

#include "ThermoStateData_bp.h"

int EncodeThermoStateData(struct ThermoStateData *m, unsigned char *s) {
    s[0] = (((unsigned char *)&((*m).magic))[0] ) & 255;
    s[1] = (((unsigned char *)&((*m).magic))[1] ) & 255;
    s[2] = (((unsigned char *)&((*m).set_point))[0] ) & 255;
    s[3] = (((unsigned char *)&((*m).fan_state))[0] ) & 7;
    s[3] |= (((unsigned char *)&((*m).heating_state))[0] << 3) & 56;
    return 0;
}

int DecodeThermoStateData(struct ThermoStateData *m, unsigned char *s) {
    ((unsigned char *)&((*m).magic))[0] = (s[0] ) & 255;
    ((unsigned char *)&((*m).magic))[1] = (s[1] ) & 255;
    ((unsigned char *)&((*m).set_point))[0] = (s[2] ) & 255;
    ((unsigned char *)&((*m).fan_state))[0] = (s[3] ) & 7;
    ((unsigned char *)&((*m).heating_state))[0] = (s[3] >> 3) & 7;
    return 0;
}