// Code generated by bitproto. DO NOT EDIT.

#include "ThermoCommEvent_bp.h"

int EncodeTempChangedEvent(struct TempChangedEvent *m, unsigned char *s) {
    s[0] = (((unsigned char *)&((*m).new_temp_f))[0] ) & 255;
    return 0;
}

int DecodeTempChangedEvent(struct TempChangedEvent *m, unsigned char *s) {
    ((unsigned char *)&((*m).new_temp_f))[0] = (s[0] ) & 255;
    return 0;
}

int EncodeSetPointChangedEvent(struct SetPointChangedEvent *m, unsigned char *s) {
    s[0] = (((unsigned char *)&((*m).new_set_point_f))[0] ) & 255;
    return 0;
}

int DecodeSetPointChangedEvent(struct SetPointChangedEvent *m, unsigned char *s) {
    ((unsigned char *)&((*m).new_set_point_f))[0] = (s[0] ) & 255;
    return 0;
}

int EncodeHeatingModeChangedEvent(struct HeatingModeChangedEvent *m, unsigned char *s) {
    s[0] = (((unsigned char *)&((*m).new_mode))[0] ) & 3;
    return 0;
}

int DecodeHeatingModeChangedEvent(struct HeatingModeChangedEvent *m, unsigned char *s) {
    ((unsigned char *)&((*m).new_mode))[0] = (s[0] ) & 3;
    return 0;
}

int EncodeSettingsChangedEvent(struct SettingsChangedEvent *m, unsigned char *s) {
    s[0] = (((unsigned char *)&((*m).new_settings.magic))[0] ) & 255;
    s[1] = (((unsigned char *)&((*m).new_settings.magic))[1] ) & 255;
    s[2] = (((unsigned char *)&((*m).new_settings.set_point))[0] ) & 255;
    s[3] = (((unsigned char *)&((*m).new_settings.temp_display_unit))[0] ) & 1;
    return 0;
}

int DecodeSettingsChangedEvent(struct SettingsChangedEvent *m, unsigned char *s) {
    ((unsigned char *)&((*m).new_settings.magic))[0] = (s[0] ) & 255;
    ((unsigned char *)&((*m).new_settings.magic))[1] = (s[1] ) & 255;
    ((unsigned char *)&((*m).new_settings.set_point))[0] = (s[2] ) & 255;
    ((unsigned char *)&((*m).new_settings.temp_display_unit))[0] = (s[3] ) & 1;
    return 0;
}