// Code generated by bitproto. DO NOT EDIT.

#ifndef __BITPROTO__THERMO_STATE_DATA_H__
#define __BITPROTO__THERMO_STATE_DATA_H__ 1

#include <inttypes.h>
#include <stddef.h>
#include <stdint.h>
#ifndef __cplusplus
#include <stdbool.h>
#endif

#if defined(__cplusplus)
extern "C" {
#endif

#define BITPROTO_OPTIMIZATION_MODE 1

#define THERMO_STATE_DATA_MAGIC 292

typedef uint8_t FanState; // 3bit

#define FAN_ON 0
#define FAN_OFF 1
#define FAN_AUTO 2

typedef uint8_t HeatingState; // 3bit

#define HEATING_HEATING 0
#define HEATING_COOLING 1
#define HEATING_NONE 2

// Number of bytes to encode struct ThermoStateData
#define BYTES_LENGTH_THERMO_STATE_DATA 4

struct ThermoStateData {
    uint16_t magic; // 16bit
    uint8_t set_point; // 8bit
    FanState fan_state; // 3bit
    HeatingState heating_state; // 3bit
};

// Encode struct ThermoStateData to given buffer s.
int EncodeThermoStateData(struct ThermoStateData *m, unsigned char *s);
// Decode struct ThermoStateData from given buffer s.
int DecodeThermoStateData(struct ThermoStateData *m, unsigned char *s);

#if defined(__cplusplus)
}
#endif

#endif